# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build & distribute an APK to Firebase App Distribution"
  lane :distribute do

    variant = UI.select("Which build variant?", ["Debug", "Release"])


    notes = UI.input("Release notes (leave blank to skip):")


    gradle(task: "clean")
    gradle(
      task: "assemble",
      build_type: variant
    )


    artifact_path = if variant == "Release"
      "app/build/outputs/apk/release/app-release-unsigned.apk"
    else
      "app/build/outputs/apk/debug/app-debug.apk"
    end

    # 5️⃣ Distribute
    firebase_app_distribution(
      app: "1:627901680389:android:6e871d0c8fc9b04200856c",
      firebase_cli_token: "1//0g4wGBSB-VetTCgYIARAAGBASNwF-L9IrCJBnbaH9Oj0Z3-pgezCtjJ_QL-71iCTQquKBbrH6emrofnvTQS9cMSdKfa15adyCtjc",
      android_artifact_path: artifact_path,
      android_artifact_type: "APK",
      groups: "bca-digital",
      release_notes: notes.empty? ? nil : notes
    )

    UI.success("✅ Uploaded #{variant} build with#{notes.empty? ? " no" : ""} release notes!")
  end
end
